<!--DXY H5通用打点-->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-69718883-17', 'auto'); // 默认UA-69718883-17，如果 PM 有单独申请 GA 码，请相应替换

  // 如需使用自定义域名和事件来统计，请参考下方代码
  ga('send', 'pageview','中秋节H5+中秋节H5'); /** 统计页面访问量 **/
  ga('send', 'event','中秋节H5+进入页面'); /** 统计用户行为 **/
  // 具体参数参考 ：
  // https://developers.google.com/analytics/devguides/collection/analyticsjs/pages
</script>
